const ActionTypes = {
  HBKK: 'LIST_KHUYENKHICH',
  HBTT: 'LIST_TAITRO',
  GET_DATA_HBKK: 'GET_DATA_KHUYENKHICH',
  GET_DATA_HBTT: 'GET_DATA_TAITRO',
  DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
  ADD_LINK_EXPORT: 'ADD_LINK_EXPORT',
};

export default ActionTypes;
