const ActionTypes = {
  HBKK: 'LIST_KYLUAT',
  HBTT: 'LIST_KHENTHUONG',
  GET_DATA_HBKK: 'GET_DATA_KYLUAT',
  GET_DATA_HBTT: 'GET_DATA_KHENTHUONG',
  DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
  ADD_LINK_PRINT: 'ADD_LINK_PRINT',
  PRINT_BY_TYPE: 'PRINT_BY_TYPE'
};

export default ActionTypes;
