const ActionTypes = {
  HBKK: 'LIST_KHUYENKHICH',
  HBTT: 'LIST_TAITRO',
  TK: 'LIST_TK',
  GET_NULL_DATA: 'GET_NULL_DATA',
  GET_DATA_HBKK: 'GET_DATA_KHUYENKHICH',
  GET_DATA_HBTT: 'GET_DATA_TAITRO',
  GET_DATA_COUNTING: 'GET_DATA_COUNTING',
  GET_DATA_FILTER: 'GET_DATA_FILTER',
  DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
  ADD_LINK_EXPORT: 'ADD_LINK_EXPORT',
};

export default ActionTypes;
