const ActionTypes = {
  TK: 'TK',
  NO_DATA: 'NO_DATA',
  GET_DATA_BHYT: 'GET_DATA_BHYT',
  GET_DATA_BHTN: 'GET_DATA_BHTN',
  GET_DATA_TTBT: 'GET_DATA_TTBT',
  GET_DATA_COUNTING: 'GET_DATA_COUNTING',
  DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
  ADD_LINK_EXPORT: 'ADD_LINK_EXPORT',
};

export default ActionTypes;
