const ActionTypes = {
  SVNN: 'SVNN',
  DTB: 'DTB',
  DSTN: 'DSTN',
  HTTC: 'HTTC',
  DH: 'DH',
  CCHV: 'CCHV',
  BTH: 'BTH',
  DKHP: 'DKHP',
  GET_LIST_SVNN: 'GET_LIST_SVNN',
  GET_LIST_DTB: 'GET_LIST_DTB',
  GET_LIST_DSTN: 'GET_LIST_DSTN',
  GET_LIST_HTTC: 'GET_LIST_HTTC',
  GET_LIST_DH: 'GET_LIST_DH',
  GET_LIST_CCHV: 'GET_LIST_CCHV',
  GET_LIST_BTH: 'GET_LIST_BTH',
  GET_LIST_DKHP: 'GET_LIST_DKHP',
  DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
  ADD_LINK_PRINT: 'ADD_LINK_PRINT',
  PRINT_BY_TYPE: 'PRINT_BY_TYPE'
};

export default ActionTypes;
