const ActionTypes = {
  GET_NULL_DATA: 'GET_NULL_DATA',
  ALL_LIST: 'ALL_LIST',
  PRINT_LIST: 'PRINT_LIST',
  IMPORT_LIST: 'IMPORT_LIST',
  HISTORY_LIST: 'HISTORY_LIST',
  HISTORY_IMPORT: 'HISTORY_IMPORT_LIST',
  GET_LIST_INFO: 'GET_LIST_INFO',
  GET_LIST_WITH_STATUS: 'GET_LIST_WITH_STATUS',
  GET_HISTORY_LIST: 'GET_HISTORY_LIST',
  GET_HISTORY_IMPORT_LIST: 'GET_HISTORY_IMPORT_LIST',
  GET_LIST_DOCX: 'GET_LIST_DOCX',
  DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
  ADD_LINK_PRINT: 'ADD_LINK_PRINT',
  ADD_LINK_EXPORT: 'ADD_LINK_EXPORT',
  EXPORT_TO_DOCX: 'EXPORT_TO_DOCX',
  GET_USER: 'GET_USER'
};

export default ActionTypes;
