const ActionTypes = {
  TK: 'TK',
  DS: 'DS',
  GET_NULL_DATA: 'GET_NULL_DATA',
  GET_LIST_DTTS: 'GET_LIST_DTTS',
  GET_LIST_HTDX: 'GET_LIST_HTDX',
  GET_LIST_TCXH: 'GET_LIST_TCXH',
  GET_LIST_MGHP: 'GET_LIST_MGHP',
  GET_LIST_SVKT: 'GET_LIST_SVKT',
  GET_LIST_MSSV: 'GET_LIST_MSSV',
  GET_DATA_FILTER: 'GET_DATA_FILTER',
  ADD_LINK_EXPORT: 'ADD_LINK_EXPORT',
};

export default ActionTypes;
