const ActionTypes = {
    ALLLIST: 'ALLLIST',
    KTX: 'KTX',
    GET_ALLLIST: 'GET_ALLLIST',
    GET_NULL_DATA: 'GET_NULL_DATA',
    GET_KTX_LIST: 'GET_KTX_LIST',
    UPDATE_STUDENT: 'UPDATE_STUDENT',
    DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
    ADD_LINK_EXPORT: 'ADD_LINK_EXPORT',
  };
  
  export default ActionTypes;
  