const ActionTypes = {
    ALLLIST: 'ALLLIST',
    KTX: 'KTX',
    GET_ALLLIST: 'GET_ALLLIST',
    GET_KTX_LIST: 'GET_KTX_LIST',
    DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
    ADD_LINK_PRINT: 'ADD_LINK_PRINT',
    PRINT_BY_TYPE: 'PRINT_BY_TYPE'
  };
  
  export default ActionTypes;
  