export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_LOGIN_FIRST_TIME="SET_LOGIN_FIRST_TIME";
export const RESET_PASSWORD="RESET_PASSWORD";
export const CONFIRM_FAIL="CONFIRM_FAIL";
export const CHANGE_PASSWORD="CHANGE_PASSWORD";
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';