const ActionTypes = {
    CHANGE_COLUMN_KT: 'CHANGE_COLUMN_KT',
    CHANGE_COLUMN_KL: 'CHANGE_COLUMN_KL',
    LIST_KYLUAT: 'LIST_KYLUAT',
    LIST_KHENTHUONG: 'LIST_KHENTHUONG',
    GET_DATA_KYLUAT: 'GET_DATA_KYLUAT',
    GET_DATA_KHENTHUONG: 'GET_DATA_KHENTHUONG',
    GET_DATA_FILTER: 'GET_DATA_FILTER',
    DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
    ADD_LINK_EXPORT: 'ADD_LINK_EXPORT',
  };
  
  export default ActionTypes;
  