const ActionTypes = {
    LIST_KYLUAT: 'LIST_KYLUAT',
    LIST_KHENTHUONG: 'LIST_KHENTHUONG',
    GET_DATA_KYLUAT: 'GET_DATA_KYLUAT',
    GET_DATA_KHENTHUONG: 'GET_DATA_KHENTHUONG',
    DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
    ADD_LINK_PRINT: 'ADD_LINK_PRINT',
    PRINT_BY_TYPE: 'PRINT_BY_TYPE'
  };
  
  export default ActionTypes;
  