const ActionTypes = {
    FOLDER: 'FOLDER',
    KQSHCD: 'KQSHCD',
    GET_LIST_FILE: 'GET_LIST_FILE',
    GET_LIST_DDSHCD: 'GET_LIST_DDSHCD',
    GET_LIST_KTSHCD: 'GET_LIST_KTSHCD',
    GET_LIST_KQSHCD: 'GET_LIST_KQSHCD',
    DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
    ADD_LINK_PRINT: 'ADD_LINK_PRINT',
    PRINT_BY_TYPE: 'PRINT_BY_TYPE'
  };
  
  export default ActionTypes;
  