const ActionTypes = {
    HISTORY_LIST: 'HISTORY_LIST',
    PRINT_LIST: 'PRINT_LIST',
    GET_NOT_PRINT_YET: 'GET_NOT_PRINT_YET',
    DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
    ADD_LINK_PRINT: 'ADD_LINK_PRINT',
    PRINT_BY_TYPE: 'PRINT_BY_TYPE'
  };
  
  export default ActionTypes;
  