const ActionTypes = {
  GET_NULL_DATA: 'GET_NULL_DATA',
  HISTORY_LIST: 'HISTORY_LIST',
  HISTORY_LIST_BY_DATE: 'HISTORY_LIST_BY_DATE',
  PRINT_LIST: 'PRINT_LIST',
  HISTORY_IMPORT_LIST: 'HISTORY_IMPORT_LIST',
  GET_USER: 'GET_USER',
  GET_NOT_PRINT_YET: 'GET_NOT_PRINT_YET',
  GET_HISTORY_LIST: 'GET_HISTORY_LIST',
  GET_HISTORY_LIST_BY_DATE: 'GET_HISTORY_LIST_BY_DATE',
  GET_HISTORY_IMPORT_LIST: 'GET_HISTORY_IMPORT_LIST',
  DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
  ADD_LINK_PRINT: 'ADD_LINK_PRINT',
  ADD_LINK_EXPORT: 'ADD_LINK_EXPORT',
  ADD_LINK_PRINT_HANDLER: 'ADD_LINK_PRINT_HANDLER',
  PRINT_BY_TYPE: 'PRINT_BY_TYPE'
};

export default ActionTypes;
