const ActionTypes = {
    HISTORY_LISST: 'HISTORY_LIST',
    PRINT_LIST: 'PRINT_LIST',
    GET_NOT_PRINT_YET: 'GET_NOT_PRINT_YET',
    DELETE_ONE_CERTIFICATE: 'DELETE_ONE_CERTIFICATE',
    ADD_LINK_PRINT: 'ADD_LINK_PRINT',
    EXPORT_TO_DOCX: 'EXPORT_TO_DOCX'
  };
  
  export default ActionTypes;
  